/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
///
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class CustomIcons  {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData lock = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_1 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData size = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData happy = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sad = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archer = IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boomerang = IconData(0xe93b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card = IconData(0xe9f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData puzzle = IconData(0xea12, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bolt = IconData(0xea2d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moonSun = IconData(0xea45, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData muscleFat = IconData(0xea47, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData muscleUp = IconData(0xea48, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playerKing = IconData(0xea68, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food = IconData(0xf0f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xf879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xf083, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bicycle = IconData(0xf206, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon_inv = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fitness = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gym = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leg = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lifting = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lifting_2 = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ligting_3 = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData habits = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loop = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bed = IconData(0xf236, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tape = IconData(0xf4db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
