/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData lock = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_circled2 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_circled2 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_outline = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_outline = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_1 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arm = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users_outline = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_add_outline = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_add = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_delete_outline = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gym = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leg = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lift = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lift_crossfit = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lift_sit = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_delete = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData happy = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_1 = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_off = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feather_wing = IconData(0xe9bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightning_bolt = IconData(0xea2d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xf007, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xf00c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData times = IconData(0xf00d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog = IconData(0xf013, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xf03d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image = IconData(0xf03e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xf044, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData times_circle = IconData(0xf057, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle = IconData(0xf058, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question_circle = IconData(0xf059, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leaf = IconData(0xf06c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xf06e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_slash = IconData(0xf070, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cogs = IconData(0xf085, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData square = IconData(0xf0c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_square = IconData(0xf0fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question = IconData(0xf128, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xf129, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamation = IconData(0xf12a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microphone = IconData(0xf130, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_circle = IconData(0xf144, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_square = IconData(0xf146, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_square = IconData(0xf14a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xf185, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xf186, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_circled2 = IconData(0xf18e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_circled2 = IconData(0xf190, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause_circle = IconData(0xf28b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop_circle = IconData(0xf28d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_alt = IconData(0xf303, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tape = IconData(0xf4db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dizzy = IconData(0xf567, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grin_wink = IconData(0xf58c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baby = IconData(0xf77c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
